[ { 
    Name: "Perul Jain",
    "Project (1 project in each row)": "Information app",
    Description: "An app which stores the information of user in firebase realtime database and information can be used for official purposes.",
    "Relevant Links": "https://github.com/peruljain",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Perul Jain",
    "Project (1 project in each row)": "Concetto app",
    Description: "Our team (me , Vanshika,  Shridhar) made this app for biggest techno-management fest of East India, CONCETTO. This app consists of information about events, workshops, tech-talks.",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Perul Jain",
    "Project (1 project in each row)": "Light detecting bot",
    Description: "An autonomous bot which follows light .",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Perul Jain",
    "Project (1 project in each row)": "Bluetooth control bot",
    Description: "An autonomous bot which is controlled by Android app",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Perul Jain",
    "Project (1 project in each row)": "obstacle avoiding bot",
    Description: "An autonomous bot which compete the path with obstacles between their path",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Suyog Jadhav",
    "Project (1 project in each row)": "DriveSmart",
    Description: "A smart system for cars that alerts the driver with visual cues and audio alerts when the driver gets distracted from the road or is drowsy. Developed a real-time headpose estimation system using TensorFlow and OpenCV. Startup funded by CIIE, IIT (ISM) Dhanbad​. Nearing completion.",
    "Relevant Links": "NDA",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Suyog Jadhav",
    "Project (1 project in each row)": "FaceSearch",
    Description: "Created a command-line tool that takes an image, detects faces in it, lets user select one and then tries to establish identity of the person by performing Google reverse Image search on the face. Used OpenCV​. Implemented in Python. Completed.",
    "Relevant Links": "https://github.com/IAmSuyogJadhav/FaceSearch",
    "Relavant Images (Google Drive Link)": "https://mlendeavours.files.wordpress.com/2018/07/facesearch.png" },
  { 
    Name: "Suyog Jadhav",
    "Project (1 project in each row)": "WalkSafe",
    Description: "A smart system for pedestrians wearing earphones, that alerts the user whenever he/she is being honked at by an oncoming car. Promises to dramatically reduce the no. of accidents caused due to pedestrians crossing streets wearing earphones. Starting 26-10-2018.",
    "Relevant Links": "https://github.com/hackabit18/CyberLabs",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Suyog Jadhav",
    "Project (1 project in each row)": "T. A. L. K.",
    Description: "Working on a startup idea in a team of three members that promises something that has never been achieved before. Using recurrent neural networks in combination with advanced conducting fibres and other hardware sensors as the core technologies. The work hasn\"t yet started.",
    "Relevant Links": "NDA",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Udbhav Bamba",
    "Project (1 project in each row)": "DriveSmart",
    Description: "A smart system for cars that alerts the driver with visual cues and audio alerts when the driver gets distracted from the road or is drowsy. Developed a real-time headpose estimation system using TensorFlow and OpenCV. Startup funded by CIIE, IIT (ISM) Dhanbad​. Nearing completion.",
    "Relevant Links": "NDA",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Udbhav Bamba",
    "Project (1 project in each row)": "WalkSafe",
    Description: "A smart system for pedestrians wearing earphones, that alerts the user whenever he/she is being honked at by an oncoming car. Promises to dramatically reduce the no. of accidents caused due to pedestrians crossing streets wearing earphones. Starting 26-10-2018.",
    "Relevant Links": "https://github.com/hackabit18/CyberLabs",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Udbhav Bamba",
    "Project (1 project in each row)": "Neural Style Transfer",
    Description: "It is the implementation of 'A Neural Algorithm of Artistic Style'\n(https://arxiv.org/pdf/1508.06576.pdf) paper by Leon A. Gatys, Alexander S. Ecker, Matthias Bethge.",
    "Relevant Links": "https://github.com/ubamba98/Neural-Style-Transfer",
    "Relavant Images (Google Drive Link)": "https://github.com/ubamba98/Neural-Style-Transfer/blob/master/output/generated_image.jpg" },
  { 
    Name: "Raj Rani",
    "Project (1 project in each row)": "One of the communication apps of Microsoft",
    Description: "NDA",
    "Relevant Links": "NDA",
    "Relavant Images (Google Drive Link)": "NDA" },
  { 
    Name: "Aniket Teotia",
    "Project (1 project in each row)": "FaceBot",
    Description: "project includes face recognition , and then playing any message that might have been left for the person as well as recording message for some other person. we intend to add additional features using trigger words.",
    "Relevant Links": "https://github.com/anikett12/Face-Recognition",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Aniket Teotia",
    "Project (1 project in each row)": "WalkSafe",
    Description: "A smart system for pedestrians wearing earphones, that alerts the user whenever he/she is being honked at by an oncoming car. Promises to dramatically reduce the no. of accidents caused due to pedestrians crossing streets wearing earphones. Starting 26-10-2018.",
    "Relevant Links": "https://github.com/hackabit18/CyberLabs",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Dev Vats",
    "Project (1 project in each row)": "FaceBot",
    Description: "project includes face recognition , and then playing any message that might have been left for the person as well as recording message for some other person. we intend to add additional features using trigger words.\n\n",
    "Relevant Links": "https://github.com/devvats/FaceBot",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Dev Vats",
    "Project (1 project in each row)": "Movie Recommender",
    Description: "With a dataset consisting of user id’s and their rating for movies they have watched , the program will be able to predict the rating for unseen movies and thus suggest movies to users.",
    "Relevant Links": "https://github.com/devvats/Movie-Recommender-System",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Tejus",
    "Project (1 project in each row)": "DriveSmart",
    Description: "A smart system for cars that alerts the driver with visual cues and audio alerts when the driver gets distracted from the road or is drowsy. Developed a real-time headpose estimation system using TensorFlow and OpenCV. Startup funded by CIIE, IIT (ISM) Dhanbad​. Nearing completion.",
    "Relevant Links": "NDA",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Tejus",
    "Project (1 project in each row)": "MNIST Regeneration",
    Description: "Recreated the Handwritten Digits from the MNIST Dataset using a Generative Adversarial Network(GAN), an implementation of 'Unsupervised Representation Learning with Deep Convolutional Generative Adversarial Networks' (https://arxiv.org/pdf/1511.06434) paper.",
    "Relevant Links": "https://github.com/gktejus/GAN-for-MNIST",
    "Relavant Images (Google Drive Link)": "https://github.com/gktejus/GAN-for-MNIST/blob/master/images/dcgan_generated_image_epoch_10.png" },
  { 
    Name: "NIKHIL",
    "Project (1 project in each row)": "LIGHT DETECTING BOT",
    Description: "A light detecting bot which move in direction of higher intensity of light",
    "Relevant Links": "https://github.com/nikarora1111/light-detector-.git",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "NIKHIL",
    "Project (1 project in each row)": "voltage tester of battery",
    Description: "arduino based voltage tester which tells about battery voltage",
    "Relevant Links": "https://github.com/nikarora1111/voltage-tester-of-battery-using-arduino.git",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "NIKHIL",
    "Project (1 project in each row)": "obstacle avoiding bot",
    Description: "an autonomous bot able to the path with obstacle between path",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "NIKHIL",
    "Project (1 project in each row)": "LCD module printing",
    Description: "used lcd 20*4 module to printing data (scrolling mode,blinking mode..etc)",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "News Reader",
    Description: "Fetches news from various news agencies and display them in an organised way.",
    "Relevant Links": "https://github.com/ShridharGoel/NewsReader",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Wallpaper Gallery",
    Description: "A wallpaper gallery for Android devices which contains features like downloading, sharing and\nadding to favourite list. It uses firebase as backend for storing wallpapers and other details like\ntitle, description and category.",
    "Relevant Links": "https://github.com/ShridharGoel/wallpaper-app",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Ball Runner",
    Description: "Ball Runner is a game for the android platform made with Unity.",
    "Relevant Links": "https://play.google.com/store/apps/details?id=com.dsapps.ballrunner",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Classifieds App",
    Description: "An android app which can be used as a marketplace for people to sell and buy items.",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Attendance Management App",
    Description: "A simple attendance management app which can be used by employers to maintain the attendance\nof employees. The employees are expected to login using their mobile number by OTP\nauthentication. When a person checks-in by clicking on the 'Check-in' button, his/her location\n(latitude, longitude and address) would be stored in the database along with the current\ntime. Similarly, while leaving office, the person should check-out so that the timing of checking-out\nis stored.",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Concetto App",
    Description: "Worked in a team of three to develop an app for the annual techno-management fest of IIT(ISM) Dhanbad.",
    "Relevant Links": "bit.ly/concettoapp",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "WalkSafe",
    Description: "Will be working on the android app of a smart system for pedestrians wearing earphones, that alerts the user whenever he/she is being honked at by an oncoming car. Promises to dramatically reduce the no. of accidents caused due to pedestrians crossing streets wearing earphones. Starting 26-10-2018.",
    "Relevant Links": "https://github.com/hackabit18/CyberLabs",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Score Feeder",
    Description: "web crawler developed by cricbuzz python library which fetches live scores,full score card and commentry.",
    "Relevant Links": "https://github.com/Mk-ism/Score-card-viewer",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Keylogger sender",
    Description: "key strokes hacking tool developed using pyhook library, which sends strokes data to the server.",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Image downloader and url fetcher",
    Description: "python scrapping tool that downloads all image in a webpage and shows all urls ,which is used for furter pentesting.",
    "Relevant Links": "https://github.com/Mk-ism/Image_downloaderhttps://github.com/Mk-ism/Fetch-urls",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "AR Ruler",
    Description: "AR_Ruler is a powerful application which can measure any distance between two given points in all the three axis separately. It can measure distance between any two point in cm, inch, m, foot. This is made in Unity with Vuforia.",
    "Relevant Links": "https://github.com/adityamudgil2505/AR_Ruler",
    "Relavant Images (Google Drive Link)": "https://drive.google.com/open?id=1bK3aGUu1q2owQ6vsDC3uszX6uSPUqueI" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Music Player",
    Description: "Basic Music Player using html, css, javascript",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Brick Breaker",
    Description: "A basic brickBreaker game which determines the score of an individual on the basis of the number of bricks broken by the ball. Implemented using React Native and JavaScript. Currently working on it.",
    "Relevant Links": "https://github.com/salonimohta/brickBreaker-using-React-Native",
    "Relavant Images (Google Drive Link)": "NA" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "The-Q",
    Description: "An app which aims to reduce the stress of a reality show contestant of waiting in queues for their turn by digitizing the process. Will be implemented using React Native and Restful APIs of Django(Python) .Starting on 26.10.18.",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Advanced sentiment analysis based Twitter support bot for #MeToo",
    Description: "• Used Natural Language processing and Machine learning algorithm to do a Sentiment Analysis and grade a #MeToo post. • Validated the genuinity of the post on the basis of polarity and factuality. •Analyzed emotion of the post & performed tasks such as re-tweeting the genuine post, and commenting supportive solution.",
    "Relevant Links": "https://github.com/rrishabh145/Advanced-sentiment-analysis-based-Twitter-support-bot-for-MeToo",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Time series forecasting with LSTM neural network in Keras",
    Description: "• Made multiple models to solve a forecasting problem where, given the weather conditions and pollution for prior hours, pollution at the next hour was predicted using LSTM neural network on time series data. • Extended to generalize for forecasting on multivariate as well as univariate time series data of any type.",
    "Relevant Links": "NA",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Hand written digit recognition",
    Description: "Predicted hand written digit images (MNIST) by 2 methods: •implemented one vs all classiﬁcation by training multiple regularized logistic regression classiﬁers, one each for 10 digits. • implemented the back propagation algorithm to learn the parameters for regularized neural network",
    "Relevant Links": "NA",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Shridhar Goel",
    "Project (1 project in each row)": "Miniature Weather Monitoring Station (IoT based)",
    Description: "Built an automated weather monitoring station which gives us a regular weather report of our local surrounding. With the use of a Raspberry Pi and a network of sensors, the system monitors wind speed, wind direction, air temperature, humidity, rain and solar radiation. The user gets a regular update of the surrounding weather on his/her computer through the internet cloud storage centre.",
    "Relevant Links": "NA",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Mayank kumar",
    "Project (1 project in each row)": "Awesome Text Editor",
    Description: "A graphical user friendly text editor written in python using PyQt5 module. It has many functions and tools for the user to create and edit various styles of text.",
    "Relevant Links": "https://github.com/rrishabh145/Awesome-Text-Editor",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Mayank kumar",
    "Project (1 project in each row)": "Image compressor",
    Description: "An app which compresses as well as decompresses high resolution images using  K means a widely used unsupervised machine learning algorithm.",
    "Relevant Links": "https://github.com/Samuelimza/ImageCompress",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Mayank kumar",
    "Project (1 project in each row)": "CodeOnPaper",
    Description: "An app which can compile a handwritten code i.e. by using the image of a handwritten code.Basically it first trasforms the image into text using optical character recognition and then compiles that text. Starting 26/10/2018",
    "Relevant Links": "https://github.com/hackabit18/Gizmos",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Aditya Mudgil",
    "Project (1 project in each row)": "ImageCompress",
    Description: "An app which compresses as well as decompresses high resolution images using  K means a widely used unsupervised machine learning algorithm.",
    "Relevant Links": "https://github.com/Samuelimza/ImageCompress",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Aditya Mudgil",
    "Project (1 project in each row)": "CodeOnPaper",
    Description: "An app which converts small programs written on paper to editable formats with the options to compile and run. Starting 26/10/2018",
    "Relevant Links": "https://github.com/hackabit18/Gizmos",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Saloni Mohta",
    "Project (1 project in each row)": "Autonomous Car (prototype)",
    Description: "Genetically evolved simulated cars to drive within the boundaries of a defined track.",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": " "},
  { 
    Name: "Rishabh Rajput",
    "Project (1 project in each row)": "",
    Description: "",
    "Relevant Links": "",
    "Relavant Images (Google Drive Link)": " "},
 
  { 
    Name: "Ali Sabir",
    "Project (1 project in each row)": "Image compressor",
    Description: "An app which compresses as well as decompresses high resolution images using  K means a widely used unsupervised machine learning algorithm.",
    "Relevant Links": "https://github.com/Samuelimza/ImageCompress",
    "Relavant Images (Google Drive Link)": "" },
  { 
    Name: "Ali Sabir",
    "Project (1 project in each row)": "CodeOnPaper",
    Description: "An app which can compile a handwritten code i.e. by using the image of a handwritten code.Basically it first trasforms the image into text using optical character recognition and then compiles that text. Starting 26/10/2018",
    "Relevant Links": "https://github.com/hackabit18/Gizmos",
    "Relavant Images (Google Drive Link)": "" },
]
